package com.github.aruizca.service.db.entity;

// Generated 12/10/2012 10:27:12 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LookupValueEntity generated by hbm2java
 */
@Entity
@Table(name = "LOOKUP_VALUE")
public class LookupValueEntity implements java.io.Serializable {

	private String lookupValueCode;
	private LookupTypeEntity lookupTypeEntity;
	private LookupValueEntity parentLookupValueEntity;
	private String value;
	private String description;
	private char activeYn;
	private short sortOder;


	public LookupValueEntity() {
	}

	public LookupValueEntity(LookupTypeEntity lookupTypeEntity,
                             LookupValueEntity parentLookupValueEntity, String value, char activeYn,
                             short sortOder) {
		this.lookupTypeEntity = lookupTypeEntity;
		this.parentLookupValueEntity = parentLookupValueEntity;
		this.value = value;
		this.activeYn = activeYn;
		this.sortOder = sortOder;
	}

	@Id
	@Column(name = "LOOKUP_VALUE_CODE", unique = true, nullable = false, length = 15)
	public String getLookupValueCode() {
		return this.lookupValueCode;
	}

	public void setLookupValueCode(String lookupValueCode) {
		this.lookupValueCode = lookupValueCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOOKUP_TYPE_CODE", nullable = false)
	public LookupTypeEntity getLookupTypeEntity() {
		return this.lookupTypeEntity;
	}

	public void setLookupTypeEntity(LookupTypeEntity lookupTypeEntity) {
		this.lookupTypeEntity = lookupTypeEntity;
	}

	@Column(name = "VALUE", nullable = false, length = 4000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ACTIVE_YN", nullable = false, length = 1)
	public char getActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(char activeYn) {
		this.activeYn = activeYn;
	}

	@Column(name = "SORT_ODER", nullable = false, precision = 4, scale = 0)
	public short getSortOder() {
		return this.sortOder;
	}

	public void setSortOder(short sortOder) {
		this.sortOder = sortOder;
	}

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name = "PARENT_LOOKUP_VALUE_CODE")
	public LookupValueEntity getParentLookupValueEntity() {
		return this.parentLookupValueEntity;
	}

	public void setParentLookupValueEntity(LookupValueEntity parentLookupValueEntity) {
		this.parentLookupValueEntity = parentLookupValueEntity;
	}

}
