package com.github.aruizca.service.db.entity;

// Generated 17/04/2012 3:45:49 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import javax.persistence.*;

/**
 * UserDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "USER_DETAIL")
public class UserDetailEntity implements java.io.Serializable {

	private Integer userId;
	private UserEntity userEntity;
	private String firstName;
	private String surname;

	public UserDetailEntity() {
	}

	public UserDetailEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	public UserDetailEntity(UserEntity userEntity, String firstName, String surname) {
		this.userEntity = userEntity;
		this.firstName = firstName;
		this.surname = surname;
	}
	
	@Id
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userEntity"))
	@GeneratedValue(generator = "generator")
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "FIRST_NAME", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "SURNAME", length = 50)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
