package com.github.aruizca.service.db.entity;

// Generated 17/04/2012 3:45:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class UserEntity implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String email;
	private UserDetailEntity userDetailEntity;
	private Set<RoleEntity> roleEntities = new HashSet<RoleEntity>(0);

    private String roleName;

	public UserEntity() {
	}

	public UserEntity(Integer userId, String username, String password, String email) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public UserEntity(Integer userId, String username, String password, String email,
                      UserDetailEntity userDetailEntity, Set<RoleEntity> roleEntities) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.email = email;
		this.userDetailEntity = userDetailEntity;
		this.roleEntities = roleEntities;
	}

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
    @SequenceGenerator(name="USERS_SEQ", sequenceName="USERS_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="USERS_SEQ")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USERNAME", nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userEntity", cascade = CascadeType.ALL)
	public UserDetailEntity getUserDetailEntity() {
		return this.userDetailEntity;
	}

	public void setUserDetailEntity(UserDetailEntity userDetailEntity) {
		this.userDetailEntity = userDetailEntity;
	}

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.DETACH)
	@JoinTable(name = "USER_ROLE", joinColumns = { @JoinColumn(name = "USER_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
	public Set<RoleEntity> getRoleEntities() {
		return this.roleEntities;
	}

	public void setRoleEntities(Set<RoleEntity> roleEntities) {
		this.roleEntities = roleEntities;
	}

    @Transient
    public String getRoleName() {
        if (roleEntities.size() > 0) {
            roleName = this.roleEntities.iterator().next().getRoleName();
        }

        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}
